# Generated by Django 5.2.14 on 2026-05-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
                ('title', models.CharField(max_length=512)),
                ('summary', models.TextField(blank=True)),
                ('source_feed', models.CharField(db_index=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Parsed from RSS when present; otherwise null.', null=True)),
                ('first_ingested_at', models.DateTimeField(auto_now_add=True)),
                ('last_ingested_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-first_ingested_at'],
                'indexes': [models.Index(fields=['-published_at'], name='markets_new_publish_4cfac1_idx')],
            },
        ),
    ]
