# Generated by Django 5.2.14 on 2026-05-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='topic_slug',
            field=models.CharField(blank=True, db_index=True, help_text='Guardian/other thematic bucket (fed_rates, geopolitics, …).', max_length=64),
        ),
        migrations.CreateModel(
            name='MacroObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='fred', max_length=16)),
                ('series_id', models.CharField(db_index=True, max_length=32)),
                ('series_title', models.CharField(blank=True, max_length=255)),
                ('observation_date', models.DateField(db_index=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('raw_value', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['-observation_date'],
                'indexes': [models.Index(fields=['series_id', '-observation_date'], name='markets_mac_series__fcf222_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'series_id', 'observation_date'), name='uniq_macro_observation')],
            },
        ),
    ]
