# Generated by Django 5.2.14 on 2026-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_newsarticle_topic_slug_macroobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, default='BTCUSDT', max_length=24)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('outcome', models.CharField(choices=[('OPEN', 'Open'), ('WIN', 'Win'), ('LOSS', 'Loss'), ('FLAT', 'Flat')], db_index=True, default='OPEN', max_length=8)),
                ('quantity', models.FloatField()),
                ('entry_price_usdt', models.FloatField()),
                ('exit_price_usdt', models.FloatField(blank=True, null=True)),
                ('stop_loss_price', models.FloatField(blank=True, null=True)),
                ('take_profit_price', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('pnl_usdt', models.FloatField(default=0.0)),
                ('pnl_pct', models.FloatField(default=0.0)),
                ('signal_snapshot', models.JSONField(blank=True, default=dict)),
                ('model_version', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['symbol', '-opened_at'], name='markets_pap_symbol_b1c19e_idx'), models.Index(fields=['outcome', '-opened_at'], name='markets_pap_outcome_4ded35_idx')],
            },
        ),
    ]
